# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from amem.v1 import amem_pb2 as amem_dot_v1_dot_amem__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in amem/v1/amem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AmemServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordBehavior = channel.unary_unary(
                '/amem.v1.AmemService/RecordBehavior',
                request_serializer=amem_dot_v1_dot_amem__pb2.RecordBehaviorRequest.SerializeToString,
                response_deserializer=amem_dot_v1_dot_amem__pb2.RecordBehaviorResponse.FromString,
                _registered_method=True)
        self.RecordProfileStatement = channel.unary_unary(
                '/amem.v1.AmemService/RecordProfileStatement',
                request_serializer=amem_dot_v1_dot_amem__pb2.RecordProfileStatementRequest.SerializeToString,
                response_deserializer=amem_dot_v1_dot_amem__pb2.RecordProfileStatementResponse.FromString,
                _registered_method=True)
        self.GetMusicProfile = channel.unary_unary(
                '/amem.v1.AmemService/GetMusicProfile',
                request_serializer=amem_dot_v1_dot_amem__pb2.GetMusicProfileRequest.SerializeToString,
                response_deserializer=amem_dot_v1_dot_amem__pb2.MusicProfileResponse.FromString,
                _registered_method=True)
        self.ExplainRecommendation = channel.unary_unary(
                '/amem.v1.AmemService/ExplainRecommendation',
                request_serializer=amem_dot_v1_dot_amem__pb2.ExplainRecommendationRequest.SerializeToString,
                response_deserializer=amem_dot_v1_dot_amem__pb2.ExplainRecommendationResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/amem.v1.AmemService/Health',
                request_serializer=amem_dot_v1_dot_amem__pb2.HealthRequest.SerializeToString,
                response_deserializer=amem_dot_v1_dot_amem__pb2.HealthResponse.FromString,
                _registered_method=True)


class AmemServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecordBehavior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordProfileStatement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMusicProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AmemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordBehavior,
                    request_deserializer=amem_dot_v1_dot_amem__pb2.RecordBehaviorRequest.FromString,
                    response_serializer=amem_dot_v1_dot_amem__pb2.RecordBehaviorResponse.SerializeToString,
            ),
            'RecordProfileStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordProfileStatement,
                    request_deserializer=amem_dot_v1_dot_amem__pb2.RecordProfileStatementRequest.FromString,
                    response_serializer=amem_dot_v1_dot_amem__pb2.RecordProfileStatementResponse.SerializeToString,
            ),
            'GetMusicProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMusicProfile,
                    request_deserializer=amem_dot_v1_dot_amem__pb2.GetMusicProfileRequest.FromString,
                    response_serializer=amem_dot_v1_dot_amem__pb2.MusicProfileResponse.SerializeToString,
            ),
            'ExplainRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainRecommendation,
                    request_deserializer=amem_dot_v1_dot_amem__pb2.ExplainRecommendationRequest.FromString,
                    response_serializer=amem_dot_v1_dot_amem__pb2.ExplainRecommendationResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=amem_dot_v1_dot_amem__pb2.HealthRequest.FromString,
                    response_serializer=amem_dot_v1_dot_amem__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amem.v1.AmemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('amem.v1.AmemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AmemService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amem.v1.AmemService/RecordBehavior',
            amem_dot_v1_dot_amem__pb2.RecordBehaviorRequest.SerializeToString,
            amem_dot_v1_dot_amem__pb2.RecordBehaviorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordProfileStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amem.v1.AmemService/RecordProfileStatement',
            amem_dot_v1_dot_amem__pb2.RecordProfileStatementRequest.SerializeToString,
            amem_dot_v1_dot_amem__pb2.RecordProfileStatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMusicProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amem.v1.AmemService/GetMusicProfile',
            amem_dot_v1_dot_amem__pb2.GetMusicProfileRequest.SerializeToString,
            amem_dot_v1_dot_amem__pb2.MusicProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amem.v1.AmemService/ExplainRecommendation',
            amem_dot_v1_dot_amem__pb2.ExplainRecommendationRequest.SerializeToString,
            amem_dot_v1_dot_amem__pb2.ExplainRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amem.v1.AmemService/Health',
            amem_dot_v1_dot_amem__pb2.HealthRequest.SerializeToString,
            amem_dot_v1_dot_amem__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
